services:
  gnn:
    build: .
    shm_size: "4g"
    ipc: "host"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true
    volumes:
      - ./results:/app/results
