import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_geometric.nn as pyg_nn

from integrators.structural_integrator import SimpleFeatureGate, FusionType


# Assumes previous classes (FusionType, SimpleFeatureGate, StructuralInformationEncoder)
# are imported or available in scope.

class StructuralGNN(nn.Module):
    """
    A multi-task GNN that fuses learnable structural embeddings with node features
    using a modular gating strategy.
    """

    def __init__(
            self,
            structural_encoder,  # Type: StructuralInformationEncoder
            input_dim: int,
            hidden_dim: int = 64,
            output_dim: int = 32,
            num_layers: int = 2,
            use_gat: bool = True,
            gate_integrator: 'StructuralSignalIntegrator' = None,  # Dependency Injection
            num_classes: int = None,
            feat_reconstruction: bool = False
    ):
        super(StructuralGNN, self).__init__()

        # ------------------------------------------------------------------
        # 1. Structural Injection & Gating
        # ------------------------------------------------------------------
        self.structural_encoder = structural_encoder
        struct_dim = self.structural_encoder.embedding_dimension

        # If no specific integrator is provided, default to the SimpleFeatureGate
        # with Concatenation fusion (mimics previous behavior).
        if gate_integrator is None:
            self.gate_integrator = SimpleFeatureGate(
                feature_dimension=input_dim,
                structural_dimension=struct_dim,
                calculation_dimension=hidden_dim,
                fusion_type=FusionType.CONCAT
            )
        else:
            self.gate_integrator = gate_integrator

        # ------------------------------------------------------------------
        # 2. Message Passing Backbone
        # ------------------------------------------------------------------
        # Note: The gate_integrator returns refined features of size 'input_dim'.
        # Therefore, the first GNN layer must project input_dim -> hidden_dim.
        self.gnn_layers = nn.ModuleList()

        # Layer 1: Adapt refined features to hidden space
        self.gnn_layers.append(pyg_nn.SAGEConv(input_dim, hidden_dim))

        # Subsequent Layers: Hidden -> Hidden
        for _ in range(num_layers - 1):
            self.gnn_layers.append(pyg_nn.SAGEConv(hidden_dim, hidden_dim))

        # Optional GAT for final attention-based aggregation
        self.use_gat = use_gat
        self.gat_layer = None
        if use_gat:
            self.gat_layer = pyg_nn.GATConv(hidden_dim, hidden_dim, heads=2, concat=False)

        # Final projection to base embedding space
        self.final_sage = pyg_nn.SAGEConv(hidden_dim, output_dim)

        # ------------------------------------------------------------------
        # 3. Task-Specific Heads
        # ------------------------------------------------------------------

        # A. Node Classification
        self.num_classes = num_classes
        if num_classes is not None:
            self.classifier = nn.Linear(output_dim, num_classes)

        # B. Feature Reconstruction (SSL)
        self.feat_reconstruction = feat_reconstruction
        if feat_reconstruction:
            self.feat_decoder = nn.Sequential(
                nn.Linear(output_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, input_dim)
            )

        # C. Link Prediction
        # Uses both GNN output and raw structural embeddings
        mlp_in_dim = (output_dim + struct_dim) * 3
        self.link_predictor = nn.Sequential(
            nn.Linear(mlp_in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1)
        )

        # D. Alignment Heads
        self.align_proj_gnn = nn.Linear(output_dim, hidden_dim)
        self.align_proj_struct = nn.Linear(struct_dim, hidden_dim)

    def forward(self, x, edge_index, node_indices=None):
        """
        Produce final embeddings for nodes.
        Returns:
            out: Final embeddings [num_nodes, output_dim]
            aux_loss: Any auxiliary loss generated by the gate (e.g., from SelfSupervisedGate)
        """
        if node_indices is None:
            node_indices = torch.arange(x.size(0), device=x.device)

        # 1. Retrieve Structural Embeddings
        struct_emb = self.structural_encoder(node_indices)

        # 2. Integrate Structure and Features via Gate
        # The integrate method handles projection, fusion, and gating internally.
        x_refined, gate_aux_loss = self.gate_integrator.integrate(
            node_features=x,
            structural_encodings=struct_emb,
            edge_indices=edge_index,
            node_indices=node_indices
        )

        # 3. Prepare for Message Passing
        # x_refined is [num_nodes, input_dim]. We pass it to the GNN.
        # We ensure the tensor is mapped to the correct device.
        out = x_refined.to(x.device)

        # 4. Message Passing
        for gnn in self.gnn_layers:
            out = gnn(out, edge_index)
            out = F.relu(out)

        if self.gat_layer is not None:
            out = self.gat_layer(out, edge_index)
            out = F.relu(out)

        # 5. Final Embedding
        out = self.final_sage(out, edge_index)

        return out, gate_aux_loss

    # ------------------------------------------------------------------
    # Loss Calculation Helpers
    # ------------------------------------------------------------------

    def classify_nodes(self, embeddings):
        if self.num_classes is None:
            raise ValueError("Classification head not initialized.")
        return self.classifier(embeddings)

    def node_classification_loss(self, embeddings, labels, mask=None):
        logits = self.classify_nodes(embeddings)
        if mask is not None:
            logits = logits[mask]
            labels = labels[mask]
        return F.cross_entropy(logits, labels)

    def link_prediction_loss(self, embeddings, edge_index, neg_sample_size=25):
        src, dst = edge_index
        num_nodes = embeddings.size(0)

        # Fetch structural embeddings for the interaction MLP
        struct_emb = self.structural_encoder(torch.arange(num_nodes, device=embeddings.device))

        neg_dst = torch.randint(0, num_nodes, (neg_sample_size * src.size(0),), device=src.device)
        neg_src = src.repeat(neg_sample_size)

        pos_score = self._pairwise_score(
            embeddings[src], embeddings[dst],
            struct_emb[src], struct_emb[dst]
        )
        neg_score = self._pairwise_score(
            embeddings[neg_src], embeddings[neg_dst],
            struct_emb[neg_src], struct_emb[neg_dst]
        )

        logits = torch.cat([pos_score, neg_score], dim=0)
        labels = torch.cat([torch.ones_like(pos_score), torch.zeros_like(neg_score)], dim=0)

        return F.binary_cross_entropy_with_logits(logits, labels)

    def _pairwise_score(self, gnn_u, gnn_v, struct_u, struct_v):
        u = torch.cat([gnn_u, struct_u], dim=-1)
        v = torch.cat([gnn_v, struct_v], dim=-1)
        uv_cat = torch.cat([u, v, u * v], dim=-1)
        return self.link_predictor(uv_cat)

    def feature_reconstruction_loss(self, embeddings, x):
        if not self.feat_reconstruction:
            return torch.tensor(0.0, device=embeddings.device)
        x_recon = self.feat_decoder(embeddings)
        return F.mse_loss(x_recon, x)

    def alignment_loss(self, embeddings, struct_target_emb):
        s_proj = self.align_proj_struct(struct_target_emb)
        g_proj = self.align_proj_gnn(embeddings)

        s_proj = F.normalize(s_proj, dim=-1)
        g_proj = F.normalize(g_proj, dim=-1)

        cos = (s_proj * g_proj).sum(dim=-1)
        return (1 - cos).mean()